#Default amount of lives a new player starts with
defaultLives: 3
#How often timerTask should repeat
timerRepeat: 20
#Distance from deathpoint dead players can travel
deathRadius: 5
#Radius of royale world
royaleMaxRadius: 1000
#Radius border will shrink to
royaleMinRadius: 900
#Minutes it will take to shrink
royaleShrinkMinutes: 5
#Minutes before it will shrink
royaleStartMins: 5