main: me.poilet66.demianarchy.DemiAnarchy
name: DemiAnarchy
version: 1.0.0
api-version: 1.16
commands:
  lives:
    description: See how many lives you have
    usage: /<command>
  royale:
    description: Starts a battle royale in the given amount of minutes.
    usage: /<command>
